name: Scrap of data
on:
  #workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Executar todas segundas-feiras (1) e quintas-feiras (4) as 9h e 18h
    - cron:  '5 0,12 * * 2,6,0'
jobs:
  scrap_football_data:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install lib pandas
      run: |
        python -m pip install --upgrade pip
        pip install pandas
    - name: Install lib requests
      run: pip install requests
      
    - name: Install lib bs4
      run: pip install bs4
      
    - name: do_scrap_football
      run: |
          echo "Starting scrap data 2012-2022.."
          python SCRIPT/scrap_football_data.py
          echo "Starting scrap data 2023"
          python SCRIPT/scrap_2023.py
          echo "Scrap done, dataset created"; ls -l CSV
                  
  
    - name: Commit changes
      uses: EndBug/add-and-commit@v9.0.1
      with:
          #author_name: Silvio
          #author_email: silviolima07@gmail.com
          default_author: github_actions
          message: 'Update dataset'
          add: 'CSV/*.csv'
          
          #pull: '--rebase --autostash ...'

    


          
        
